# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- _posts
- about.md
- blog
- categories.md
- general
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://flodur.ee'
baseurl: ''
title: 'Flodur OÜ'
description: 'Mobiilrakenduste arendus ning DevOps teenused'
email: 'rudolf@flodur.ee'
permalink: pretty

# Header nav
navigation_header:
- title: Kodu
  url: /
- title: Paadid
  url: /boats/

# Footer nav
navigation_footer:
- title: Kontakt
  url: 'mailto:rudolf@flodur.ee'
- title: Tagasi üles
  url: '#top'
